openapi: 3.0.3
info:
  description: Amazon MemoryDB for Redis is a durable, in-memory database service that delivers ultra-fast performance compatible with Redis and Memcached.
  title: Amazon MemoryDB ACLs Events API
  version: '2021-01-01'
  x-generated-from: documentation
  x-last-validated: '2026-04-19'
servers:
- description: Amazon MemoryDB API endpoint (region-specific)
  url: https://memory-db.us-east-1.amazonaws.com
security:
- awsSigV4: []
tags:
- name: Events
paths:
  /events:
    get:
      description: Returns events related to clusters, security groups, and parameter groups.
      operationId: DescribeEvents
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
              examples:
                DescribeEvents200Example:
                  summary: Default DescribeEvents 200 response
                  x-microcks-default: true
                  value:
                    result: success
          description: Success
        '400':
          description: Bad request
        '500':
          description: Internal server error
      summary: Amazon MemoryDB DescribeEvents
      tags:
      - Events
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  securitySchemes:
    awsSigV4:
      description: AWS Signature Version 4
      in: header
      name: Authorization
      type: apiKey
